# Generated by Django 2.2.3 on 2019-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('fare', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('warning', models.TextField(blank=True, null=True)),
                ('vcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('violence', models.TextField(blank=True, null=True)),
                ('ecategory', models.CharField(blank=True, max_length=20, null=True)),
                ('exposure', models.TextField(blank=True, null=True)),
                ('pcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('profanity', models.TextField(blank=True, null=True)),
                ('dcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('discrimination', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
