# Generated by Django 2.2.3 on 2019-07-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArchiveApp', '0003_auto_20190727_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': False},
        ),
    ]
